import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import '@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import  NextAuthProvider from '@/Providers/Components/nextauth.providers';
import Providers from "@/Providers/Components/ReactQueryProvider.Pronider";
  import { ToastContainer } from 'react-toastify';

const Encode = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight:['300','400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Encode.className} antialiased`}
      >
        <Providers>
          <ToastContainer></ToastContainer>
        <div className='flex flex-col justify-between  min-h-screen'>
          <NextAuthProvider>
          <Navbar/>
            <div className="container">
          <Toaster />
        {children}
        </div>
        <Footer/>
        </NextAuthProvider>
        </div>
        </Providers>

      </body>
    </html>
  );
}
